IssueTracker/IssueTracker/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IssueTracker.Models
{
    public class Tag
    {
        private ICollection<Issue> issues;

        public Tag()
        {
            issues = new HashSet<Issue>();
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50,MinimumLength = 3)]
        public string Name { get; set; }
        
        public virtual ICollection<Issue> Issues
        {
            get { return this.issues; }
            set { this.issues = value; }
        }

    }
}

IssueTracker/IssueTracker/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IssueTracker.Models;

namespace IssueTracker.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TagController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // get Index
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }


        //get List
        public ActionResult List()
        {
            List<Tag> tags = db.Tags.ToList();
            return View(tags);
        }

        // get Create
        public ActionResult Create()
        {
            return View();
        }

        // post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tag tag)
        {
            if (db.Tags.Any(t => t.Name.Equals(tag.Name)))
            {
                ModelState.AddModelError("Name", "Such tag name already exists!");
                return View(tag);
            }

            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(tag);
        }

        // get Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tag tag)
        {
            if (db.Tags.Any(t => t.Name.Equals(tag.Name)))
            {
                ModelState.AddModelError("Name", "Such tag name already exists!");
                return View(tag);
            }

            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(tag);
        }

        // get Delete
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // post Delete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IssueTracker/IssueTracker/Views/Tag/Create.cshtml
@model IssueTracker.Models.Tag

<h3>Create new tag</h3>
<hr />

@using (Html.BeginForm("Create", "Tag", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
            @Html.ActionLink("Back to list", "List", "Tag", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

IssueTracker/IssueTracker/Views/Tag/Delete.cshtml
@model IssueTracker.Models.Tag

<h3>Delete Tag</h3>
<h4>Are you sure you want to delete this tag?</h4>
<hr />

@using (Html.BeginForm("Delete", "Tag", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Name, null, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, null, new { @class = "form-control", disabled = "disabled" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to list", "List", "Tag", null, new { @class = "btn btn-primary" })
        </div>
    </div>
}

IssueTracker/IssueTracker/Views/Tag/Edit.cshtml
@model IssueTracker.Models.Tag

<h3>Edit Tag</h3>
<hr />

@using (Html.BeginForm("Edit", "Tag", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Name, null, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Back to list", "List", "Tag", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

IssueTracker/IssueTracker/Views/Tag/List.cshtml
@model List<IssueTracker.Models.Tag>

<h3>Tags list</h3>
<hr />

<p>
    @Html.ActionLink("Create New", "Create", "Tag", null, new { @class = "btn btn-primary" })
</p>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.First().Id)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.First().Name)
            </th>
            <th>
                # Issues
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tag in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(t => tag.Id)
                </td>
                <td>
                    @Html.DisplayFor(t => tag.Name)
                </td>
                <td>
                    @{
                        int issueCount = tag.Issues.Count();
                    }
                    @Html.DisplayFor(m => issueCount)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = tag.Id }, new { @class = "btn btn-primary btn-xs btn-width-xs" })
                    @Html.ActionLink("Delete", "Delete", new { id = tag.Id }, new { @class = "btn btn-primary btn-xs btn-width-xs" })
                </td>
            </tr>
         }
    </tbody>

</table>